### ISSUE TITLE
`sdk` property is missing in your `inlang.config.js`

### ISSUE THREAD

**Issue by omar2205** [ivanhofer/inlang-plugin-typesafe-i18n#4]
I followed both the getting started guides and used the `inlang.config.js` in this repo. It spat a lot of minified JS, and this:

```
Yo [Error]: The `sdk` property is missing in your `inlang.config.js` file.`. 
Make sure to use the `sdkPlugin` in your `inlang.config.js` file.
```

**Comment by omar2205** [comment]
I'm trying to use `typesafe-i18n` plugin with Inlang.

**Comment by omar2205** [comment]
So I can't use `inlang-plugin-typesafe-i18n` with the SDK?

**Comment by ivanhofer** [comment]
Yes you can, but it does not make much sense in my opinion. `typesafe-i18n` is primarly a library and if you use the inlang SDK, you will not use it as a library anymore. Just for storing translations in a `TypeScript` file.
`typesafe-i18n` has features that are currently not available in `ìnlang`. Therefore the plugin has also some limitations.

It seems you are using an older version of `@inlang/sdk-js` that does not include the link to the docs in the error message. You need to add the `sdkPlugin` in order to be able to use the inlang SDK: https://inlang.com/documentation/sdk/configuration

**Comment by ivanhofer** [comment]
please share your `inlang.config.js`

**Comment by ivanhofer** [comment]
Looks correct. What is not working? What error do you get?

**Comment by ivanhofer** [comment]
What version of the SDK have you installed?

**Comment by ivanhofer** [comment]
You probably haven't read the full error message:

```sh
Vs [Error]: Failed to setup plugin 'inlang.sdk-js':

[
  {
    "received": "Build-time",
    "code": "invalid_literal",
    "expected": "build-time",
    "path": [
      "resources",
      "cache"
    ],
    "message": "Invalid literal value, expected \"build-time\""
  }
]
```
remove those lines and it should work:
```ts
resources: {
	cache: 'Build-time'
}
```

There is a typo in the docs and `Build-time` should actually be `build-time` and therefore the setup fails. I have fixed the documentation and it should be live in a couple of minutes.

**Comment by omar2205** [comment]
`build-time` fixed it for me, too. I don't have any "type safety" tho.

**Comment by omar2205** [comment]
I meant in the `i` function, I don't have any hints.
![image](https://github.com/ivanhofer/inlang-plugin-typesafe-i18n/assets/1373867/e06b8b38-14c4-4e6b-a1b7-bafd65bc4f59)

**Comment by ivanhofer** [comment]
This is not implemented at the moment. I have created an issue where you can subscribe to: https://github.com/inlang/inlang/issues/754

**Comment by samuelstroschein** [comment]
@sudo-sand FYI as Ivan said though, you shouldn't use `sdkPlugin` and the `typesafe-i18n-plugin` at the same time. Both plugins provide an i18n lib. You only need one. 

We are updating the communication this week. If you can explain where the confusion is coming from, we can improve the docs right away :)

**Comment by ivanhofer** [comment]
@sudo-sand yes, you can use both, but it does not make that much sense. The `typesafe-i18n-plugin` is primarly meant for already existing projects that use `typesafe-i18n` as a library but want to use the inlang editor to update translations.

If you want to store translations in a `.json` file you can use the `json-plugin`.

**Comment by ivanhofer** [comment]
I made two commits to make this more clear:
https://github.com/inlang/ecosystem/commit/fc036691766d7da8d94e7a1171ff95e95e86f4f8
https://github.com/ivanhofer/inlang-plugin-typesafe-i18n/commit/8e0b8750165a1d08e98887cafcbfcbc5aaa7cb73
